name: Build XMRig Proxy

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Buid Actions Tag'

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:latest

    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@v2
        with:
          repository: caonimagfw/xmrig-proxy

      - name: Build
        run: |
          #apk add git make cmake libstdc++ gcc g++ automake libtool autoconf linux-headers bash openssl-dev
          apk add git make cmake libstdc++ gcc g++ automake libtool autoconf linux-headers bash openssl-dev
          apk add uuid-dev libmicrohttpd-dev 
          
          git clone https://github.com/libuv/libuv.git
          cd libuv
          ./autogen.sh
          ./configure
          make
          make install
          cd ..
          
          mkdir xmrig-proxy/build
          cd xmrig-proxy/build

          cmake .. -DCMAKE_BUILD_TYPE=Release -DUV_LIBRARY=/usr/lib/x86_64-linux-gnu/libuv.a
          make -j$(nproc)
          
          tar cfz aaa.tar.gz xmrig-proxy
      - name: Store generated file
        uses: actions/upload-artifact@v2
        with:
          name: aaa
          path: aaa.tar.gz
