name: Build XMRig Proxy

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Buid Actions Tag'

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:latest

    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@v2
        with:
          repository: caonimagfw/xmrig-proxy

      - name: Build
        run: |
          apk add git make cmake libstdc++ gcc g++ automake libtool autoconf linux-headers bash openssl-dev
         
          git clone https://github.com/libuv/libuv.git
          cd libuv
          ./autogen.sh
          ./configure
          make
          make install
          cd ..
          
          git clone https://github.com/open-mpi/hwloc.git
          cd hwloc
          git checkout f20635765b4b47d5339fed0ba197bd79368684cf
          ./autogen.sh
          ./configure
          make
          make install
          cmake .. -DCMAKE_BUILD_TYPE=Release -DUV_LIBRARY=/usr/lib64/libuv.a
        
          # cmake .. -DUV_INCLUDE_DIR=path/to/libuv/include -DUV_LIBRARY=path/to/libuv.a
          cd ..
          echo "XMRIG_PROXY_VERSION="`cat src/version.h | grep -Eo "APP_VERSION\s+\"(.+?)\"" | awk -F "\"" '{print $2}'` >> $GITHUB_ENV
          mkdir build
          cd scripts && ./build_deps.sh && cd ../build
          cmake .. -DXMRIG_DEPS=scripts/deps -DBUILD_STATIC=ON
          make -j$(nproc)
      - name: Store generated file
        uses: actions/upload-artifact@v2
        with:
          name: xmrig-proxy-${{ env.XMRIG_PROXY_VERSION }}
          path: build/xmrig-proxy
